title: Sketching Developer
title_separator: "-"
locale: en-GB
description: "Sketching my way through developer topics"
favicon: "/assets/images/logo.png"
avatar: "/assets/images/logo.png"
comments: false
url: https://sketchingdev.co.uk
atom_feed:
  path: # blank (default) uses feed.xml
twitter:
  username: SketchingDev
github:
  username: SketchingDev

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site Author
author:
  name: "SketchingDev" # appears in the footer and atom feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  sketchnotes:
    output: true
    permalink: /:collection/:title.html

feed:
  collections:
    - sketchnotes
    - posts

permalink: /blog/:title.html

# Without this building the website fails, saying it can't find the
# Primer theme - which is correct as I removed all themes from the
# Gemfile.lock when GitHub complained that the Primer theme wasn't
# supported and yet kept being used as a theme in spite of any config
# in here
theme:
