title: The Sketching Developer
title_separator: "-"
description: "Sketching my way through developer topics"
baseurl: ""
url: ""
favicon: "/assets/images/logo.png"
avatar: "/assets/images/logo.png"
comments: false
atom_feed:
  path: # blank (default) uses feed.xml
twitter:
  username: SketchingDev
github:
  username: SketchingDev
analytics:
  google:
    tracking_id: UA-117483921-1

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    css_class: 'highlight ui segment'

plugins:
  - jekyll-feed

# Site Author
author:
  name: "SketchingDev" # appears in the footer and atom feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed

permalink: /blog/:title.html
